wandb_version: 1

learning_rate:
  desc: null
  value: 0.1
data:
  desc: null
  value: cells
step:
  desc: null
  value: 30
seed:
  desc: null
  value: 4764
max dimension:
  desc: null
  value: 32
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1689358896.551509
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.8.16
      5: 0.15.5
      8:
      - 1
      - 3
      - 5
